language: ruby
cache: bundler
rvm:
- 2.5.3
script:
- bundle exec rspec --format doc
deploy:
  provider: rubygems
  api_key:
    secure: G6hJ87Id7v5TxP2nUkfRoErNjDtQlkGawn95q63d5y++hlT1YNspUvY8H1OXj03k/MqB7fbo4Oi6Hy60M9UCgO209F+QtBm8QAGK3QWdT8FqZ7p7AiCD4zwp0q9fBlbcRxA0sx/MQ5paq7BksxPm4texf7J8TIwju8NX2xXgIMlIh0SffQYGOAZef6qwdUxkAvqErTylEaaRR1L9jy+TNPjx6EF79V/w+g9oLdh485HkLlYWSjl6XLdJVgg7++eZn5o2lLgtzRDIm/LTjS3mGdnfWWT6XSgpinO9Pq+qj2S3FCQekfsHEWH5jwvzVioNeZabMFGyU/E1XBf/AOZf3cEffvZDS3eFisUiKMHSQA7jiVJKMkf3+x4eWujCU+Rx4eqZHj0xqLuUdZXGvpyPZPWe5R8oAVa5Exgt8dGgigvSIOhU850Wa1izSvrhIN54puudxfncVhr3qTRjOEiwXXs6Lo+Rtfvl1Y8w03XoNPeq1KxiTwTC55HybCRrVdlKjT5zKrZ5TVYEFJfcs52Vz3cU9jGs4Hiej1cjJdAxauzWbf2OntYmrQrrTtIaFvNDzNZkDhj7umO1uC1S0WLgPh8NPMnQ6R7wdgY4TBbatwcK9sb3Lrcu/nsFjvqNWu5lf5PfJQ/vFjhiGPJ71V8aX1elyYKoL/itsb3U7+/5dZg=
